adminUser:
  password: vault:cloakfancy/adminUser:password
  username: admin
dashboardAuthID: vault:cloakfancy:dashboardAuthID
dashboardAuthOrg: arcalos-dashboard
dashboardAuthSecret: vault:cloakfancy:dashboardAuthSecret
dashboardGrpchost: dex.jx
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:cloakfancy/pipelineUser:token
  username: jenkins-x-bot-test
prow:
  hmacToken: vault:cloakfancy/prow:hmacToken
